In [135]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [136]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [137]:
import zipfile

zip_path = '/content/drive/MyDrive/AI_model/data/archive.zip'
extract_path = '/content/data'

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Đã giải nén!")

Đã giải nén!

In [138]:
train_vn = pd.read_csv(
    '/content/data/train.csv'
)

In [139]:
print("Train:", train_vn.shape)


display(train_vn.head())

Train: (2000, 21)

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1

In [140]:
print(train_vn.isnull().sum())

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [141]:
print(train_vn.isnull().sum())

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [142]:
numeric_cols = train_vn.select_dtypes(
    include=np.number
).columns.tolist()

# Không đưa biến mục tiêu vào danh sách cần chuẩn hóa
numeric_cols.remove('price_range')

categorical_cols = train_vn.select_dtypes(
    include=['object', 'category', 'bool']
).columns.tolist()

print("Numerical:", numeric_cols)
print("Categorical:", categorical_cols)

Numerical: ['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g', 'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height', 'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g', 'touch_screen', 'wifi']
Categorical: []

In [143]:
from sklearn.preprocessing import StandardScaler

In [144]:
from sklearn.preprocessing import StandardScaler

# Tách X và y
X = train_vn.drop(columns=['price_range'])
y = train_vn['price_range'].astype(int)

print("y dtype:", y.dtype)
print("y unique:", sorted(y.unique()))

# Các cột số cần chuẩn hóa
numeric_cols = [
    'battery_power',
    'clock_speed',
    'fc',
    'int_memory',
    'm_dep',
    'mobile_wt',
    'n_cores',
    'pc',
    'px_height',
    'px_width',
    'ram',
    'sc_h',
    'sc_w',
    'talk_time'
]

# Chỉ scale X
scaler = StandardScaler()
X[numeric_cols] = scaler.fit_transform(X[numeric_cols])

y dtype: int64
y unique: [np.int64(0), np.int64(1), np.int64(2), np.int64(3)]

In [145]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [146]:
print("X_train:", X_train.shape)
print("X_val:", X_val.shape)
print("y_train:", y_train.shape)
print("y_val:", y_val.shape)

X_train: (1600, 20)
X_val: (400, 20)
y_train: (1600,)
y_val: (400,)

In [147]:
preprocessor = StandardScaler() # Khởi tạo preprocessor
X_train_processed = preprocessor.fit_transform(X_train)

X_val_processed = preprocessor.transform(X_val)

In [148]:
print("X_train_processed shape:", X_train_processed.shape)
print("X_val_processed shape:", X_val_processed.shape)

X_train_processed shape: (1600, 20)
X_val_processed shape: (400, 20)

In [149]:
scaler = StandardScaler()

In [150]:
X_train_scaled = scaler.fit_transform(X_train)

In [151]:
X_val_scaled = scaler.transform(X_val)

In [152]:
print("X_train_scaled:", X_train_scaled.shape)
print("X_val_scaled:", X_val_scaled.shape)

X_train_scaled: (1600, 20)
X_val_scaled: (400, 20)

In [153]:
output_dir = '/content/drive/MyDrive/AI_model/src/processed_data'

os.makedirs(output_dir, exist_ok=True)

In [154]:
display(pd.DataFrame(
    X_train_scaled,
    columns=X_train.columns
).head())

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
0,1.548360,-0.981423,-1.236230,0.970437,0.620111,-1.046060,0.754832,-0.008935,1.425710,-1.547446,0.020269,0.275712,1.181997,-0.580476,-0.528061,0.759509,-1.445123,0.557137,0.990050,1.002503
1,-1.379535,1.018929,0.837112,-1.030464,-0.993561,0.955968,0.919763,-1.403674,-0.046246,1.510316,-1.476497,-0.258762,-0.556547,1.336453,-0.290196,-1.084869,0.915929,0.557137,0.990050,1.002503
2,-0.010914,-0.981423,-0.748385,0.970437,-0.532512,0.955968,1.359577,-1.403674,1.340790,-1.547446,0.685498,-0.285711,-1.020159,-0.657302,0.423400,1.451150,1.642407,0.557137,-1.010051,1.002503
3,-1.043621,-0.981423,-0.504462,-1.030464,-0.532512,-1.046060,0.315017,-0.357620,1.623858,0.199847,-0.478653,-0.764042,0.984962,1.288322,0.185535,0.528962,-1.081884,-1.794892,-1.010051,1.002503
4,0.488416,1.018929,-1.236230,0.970437,0.620111,-1.046060,-1.389265,-0.357620,-1.008680,0.199847,0.352883,0.401470,-0.336332,-0.489767,-1.479523,-0.162680,1.642407,0.557137,-1.010051,1.002503

In [155]:
import os
output_dir = '/content/drive/MyDrive/AI_model/src/processed_data'

os.makedirs(output_dir, exist_ok=True)

In [156]:
print("y_train dtype:", y_train.dtype)
print("y_train unique:", sorted(y_train.unique()))
print("y_train min:", y_train.min())
print("y_train max:", y_train.max())

y_train dtype: int64
y_train unique: [np.int64(0), np.int64(1), np.int64(2), np.int64(3)]
y_train min: 0
y_train max: 3

In [157]:
import joblib
joblib.dump(
    X_train_scaled,
    f'{output_dir}/X_train.pkl'
)

joblib.dump(
    X_val_scaled,
    f'{output_dir}/X_val.pkl'
)

joblib.dump(
    y_train,
    f'{output_dir}/y_train.pkl'
)

joblib.dump(
    y_val,
    f'{output_dir}/y_val.pkl'
)

['/content/drive/MyDrive/AI_model/src/processed_data/y_val.pkl']

In [158]:
joblib.dump(
    scaler,
    f'{output_dir}/scaler.pkl'
)

['/content/drive/MyDrive/AI_model/src/processed_data/scaler.pkl']